name 'unzip'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures unzip'
long_description 'Installs/Configures unzip'
version '0.1.0'

depends 'windows'
depends 'iis'